spring:
  cloud:
    config:
      enabled: false

  flyway:
    locations: classpath:db/migration
    encoding: UTF-8
    user: slimatech
    password: slimatech

  logging:
    config: classpath:xml/logback-${spring.profiles.active}.xml

  profiles:
    active: dev  # Ensure this matches the active profile you're working with

# Remove the duplicate config entry
